# Generated by Django 3.0.8 on 2020-07-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('text', models.TextField(max_length=200, verbose_name='TEXT')),
                ('date', models.DateTimeField(verbose_name='DATE')),
            ],
            options={
                'verbose_name': 'News updates',
            },
        ),
        migrations.CreateModel(
            name='New_Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('date', models.DateTimeField(verbose_name='DATE')),
                ('duration', models.IntegerField(verbose_name='DURATION')),
            ],
            options={
                'verbose_name': 'Tracks updates',
            },
        ),
        migrations.CreateModel(
            name='New_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('date', models.DateTimeField(verbose_name='DATE')),
                ('link', models.CharField(max_length=1000, verbose_name='LINK')),
            ],
            options={
                'verbose_name': 'Video updates',
            },
        ),
    ]
