# Generated by Django 3.0.8 on 2020-07-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new_text',
            options={'verbose_name': 'News updates', 'verbose_name_plural': 'News updates'},
        ),
        migrations.AlterModelOptions(
            name='new_track',
            options={'verbose_name': 'Tracks updates', 'verbose_name_plural': 'Tracks updates'},
        ),
        migrations.AlterModelOptions(
            name='new_video',
            options={'verbose_name': 'Video updates', 'verbose_name_plural': 'Video updates'},
        ),
    ]
