# Generated by Django 3.0.8 on 2020-07-13 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200711_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('date', models.DateTimeField(verbose_name='DATE')),
                ('duration', models.IntegerField(verbose_name='DURATION')),
                ('likes', models.IntegerField(verbose_name='LIKES')),
            ],
        ),
        migrations.AlterModelOptions(
            name='new_text',
            options={'verbose_name': 'Announcements', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='new_track',
            options={'verbose_name': 'Tracks', 'verbose_name_plural': 'Tracks'},
        ),
        migrations.AlterModelOptions(
            name='new_video',
            options={'verbose_name': 'Videos', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='new_track',
            name='track_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='tracks'),
            preserve_default=False,
        ),
    ]
