# Generated by Django 3.0.8 on 2020-07-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200713_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_text',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='new_track',
            old_name='track_file',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='new_video',
            old_name='link',
            new_name='content',
        ),
    ]
