# Generated by Django 3.0.8 on 2020-07-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200715_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_track',
            name='duration',
        ),
    ]
