# Generated by Django 3.0.8 on 2020-08-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_new_track_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='AUTHOR NAME')),
                ('author_photo', models.ImageField(upload_to='images')),
                ('author_text', models.TextField(max_length=5000, verbose_name='TEXT')),
                ('author_links', models.TextField(max_length=2000, verbose_name="LINKS (separate with ';;')")),
            ],
            options={
                'verbose_name': 'Author',
            },
        ),
    ]
