# Generated by Django 3.0.8 on 2020-08-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Author'},
        ),
        migrations.AddField(
            model_name='author',
            name='author_pseudo',
            field=models.CharField(default='default', max_length=50, verbose_name='AUTHOR PSEUDO'),
            preserve_default=False,
        ),
    ]
