# Generated by Django 3.0.8 on 2020-08-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200812_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AddField(
            model_name='new_track',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='LIKES'),
            preserve_default=False,
        ),
    ]
