# Generated by Django 3.0.8 on 2020-09-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200817_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_links',
            field=models.TextField(blank=True, max_length=2000, verbose_name="LINKS (separate with ';;')"),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='AUTHOR NAME'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_text',
            field=models.TextField(blank=True, max_length=5000, verbose_name='TEXT'),
        ),
    ]
